### ISSUE TITLE
Fix license text in packaging

### ISSUE THREAD

**Issue by ntessore** [glass-dev/glass#431]
### Add your issue here

The license field currently contains the entire body of the license, when it should only say `MIT License`. Probably only requires

```toml
[project]
license = {text = "MIT License"}
```

as described [here](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license).
